### ISSUE TITLE
poll.poll(timeout) typo in documentation 

### ISSUE THREAD

**Issue by LupascuAndrei** [eerimoq/pumbaa#22]
Not really an issue,more like a typo in documentation. Everything works fine, just that poll.poll(timeout) expects the time given to be in seconds,instead of miliseconds. 
https://media.readthedocs.org/pdf/pumbaa/latest/pumbaa.pdf
![image](https://cloud.githubusercontent.com/assets/17813632/21813312/7c3abe94-d75e-11e6-9f16-c3ff37c07ac1.png)

**Comment by eerimoq** [comment]
Okidoki, I'll fix it.

Btw, what is the name of your project? What does the application do? Always intresting to know, so I can improve the most used and requested features =)

**Comment by LupascuAndrei** [comment]
it's a simple implementation of socket io client. tl; dr : you can remotely control other devices in your home
what i'm going to do next is to implement a way to upload a new sketch over wifi and to also update your pumbaa to the latest version over wifi.
i have an idea of how to do the sketch part ( http client , check for new python file, download it if needed, import separate sketch and run it ) 
is there an easy, already implemented way to update your firmware over wifi? if not, do you have anything in mind?
thank you very much for your support

**Comment by eerimoq** [comment]
OTA has not been prioritized. Maybe I should reconsider that =)

**Comment by LupascuAndrei** [comment]
You are some kind of divine force for me right now. 
Thank you :D

**Comment by LupascuAndrei** [comment]
Any updates on the OTA module ? :D

**Comment by eerimoq** [comment]
The idea is to run a HTTP server on the board and use an HTTP POST request to upload new software. No idea when it can be ready =)

Also, I implemented a TFTP server as an alternative method of uploading software to the board. Just have to make the "fs" module more generic so one can register a "filesystem" that writes the uploaded file to the application area in flash instead of a normal file.
